target 'Everything'
pod 'AFNetworking', '~>3.0.4'
pod 'SDAutoLayout', '~>2.1.3'
pod 'MJRefresh', '~>3.1.10'
pod 'MBProgressHUD', '~>0.9.2'
pod 'YYModel', '~>1.0.4'
pod 'YYText', '~>1.0.5'
pod 'YYImage', '~>1.0.2'
pod 'YYCache', '~>1.0.3'
pod 'SDWebImage', '~>3.8.1'
pod 'JSPatch', '~>1.1'
pod 'CocoaSecurity'
pod 'LCActionSheet'

use_frameworks!
pod 'ReactiveCocoa', '~>4.2.1'
